export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_RESQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
export const ID_REQUEST = 'ID_REQUEST';

export const OPERATOR_REQUEST = 'OPERATOR_REQUEST';
export const OPERATOR_SUCCESS = 'OPERATOR_SUCCESS';
export const OPERATOR_FAILURE = 'OPERATOR_FAILURE';
export const OPERATOR_UPDATE_SUCCESS = 'OPERATOR_UPDATE_SUCCESS';
export const OPERATOR_UPDATE_FAILURE = 'OPERATOR_UPDATE_FAILURE';

export const SPECIALTY_REQUEST = 'SPECIALTY_REQUEST';
export const SPECIALTY_SUCCESS = 'SPECIALTY_SUCCESS';
export const SPECIALTY_FAILURE = 'SPECIALTY_FAILURE';
